---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bucket-hat-os
description: Matthew's personal OS image.
base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: chezmoi
    repository: "https://github.com/ScaryOrca/dotfiles"
    file-conflict-policy: replace

  - type: dnf
    install:
      packages:
        - NetworkManager-tui
        - Thunar
        - alacritty
        - blueman
        - brightnessctl
        - dunst
        - gnome-boxes
        - gnome-keyring-pam
        - google-go-mono-fonts
        - greetd
        - gvfs
        - helix
        - kanshi
        - kmscon
        - kmscon-gl
        - kmscon-pango
        - labwc
        - labwc-session
        - lxqt-policykit
        - mksh
        - polkit
        - pulseaudio-utils
        - rofi
        - swaybg
        - swayidle
        - swaylock
        - tmux
        - tuigreet
        - waydroid
        - xdg-desktop-portal-wlr
        - zathura
        - zathura-plugins-all
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: script
    scripts:
      - build-kew.sh

  - type: systemd
    system:
      enabled:
        - greetd.service
        - kmsconvt@.service
      disabled:
        - kmsconvt@tty1.service

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: user
        install:
          - org.mozilla.firefox

  - type: signing
