---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bucket-hat-os
description: Matthew's personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-bootc
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - alsa-sof-firmware
        - amd-ucode-firmware
        - bash
        - curl
        - git
        - gstreamer1-plugin-dav1d
        - gstreamer1-plugin-libav
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-good
        - gstreamer1-plugins-ugly-free
        - helix
        - intel-audio-firmware
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - labwc
        - labwc-session
        - libva-intel-media-driver
        - linux-firmware
        - man-db
        - man-pages
        - mesa-dri-drivers
        - mesa-vulkan-drivers
        - microcode_ctl
        - mksh
        - NetworkManager
        - NetworkManager-wifi
        - rpm
        - rpm-ostree
        - systemd
        - thermald
        - tmux
        - which
        - wpa_supplicant
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-wlr
        - xorg-x11-server-Xwayland

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: user
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
